"""add complexity and effort to ideas

Revision ID: ff17af10c29d
Revises: 5722873803ca
Create Date: 2026-04-06 19:40:15.345162

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff17af10c29d'
down_revision: str | Sequence[str] | None = '5722873803ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('complexity', sa.Enum('simple', 'medium', 'complex', name='ideacomplexity'), nullable=True))
    op.add_column('ideas', sa.Column('effort', sa.Enum('quick', 'halfday', 'day', 'longterm', name='ideaeffort'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ideas', 'effort')
    op.drop_column('ideas', 'complexity')
    # ### end Alembic commands ###
